#!/bin/bash

BTW4_SINK='alsa_output.usb-Creative_Technology_Ltd_Creative_BT-W4_74C0CA82E8E6A9C32000-02.analog-stereo'
BTW4_SOURCE='alsa_input.usb-Creative_Technology_Ltd_Creative_BT-W4_74C0CA82E8E6A9C32000-02.mono-fallback'

ONBOARD_SINK='alsa_output.pci-0000_00_1f.3-platform-skl_hda_dsp_generic.HiFi__hw_sofhdadsp__sink'
ONBOARD_SOURCE='alsa_input.pci-0000_00_1f.3-platform-skl_hda_dsp_generic.HiFi__hw_sofhdadsp_6__source'

CURRENT=$(pactl get-default-sink)

if [ $CURRENT = $ONBOARD_SINK ]; then
  pactl set-default-sink "$BTW4_SINK"
  pactl set-default-source "$BTW4_SOURCE";
  notify-send ' Using BT-W4';
else
  pactl set-default-sink "$ONBOARD_SINK";
  pactl set-default-source "$ONBOARD_SOURCE";
  notify-send ' Using Onboard';
fi

